// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Lock$Type } from "./Lock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Lock"]: Lock$Type;
    ["Lock2.sol:Lock"]: Lock$Type;
  }
}
